version: '{branch}-{build}'

configuration: Release

before_build:
- cmd: nuget restore

artifacts:
  - path: .\PandaSharp.Bamboo\bin\Release
    name: PandaSharp

test_script:
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor
  
build:
  publish_nuget: true
  verbosity: minimal
  
deploy:
  - provider: NuGet
    name: Push to NuGet
    api_key:
      secure: 3bVQSfmfWu/xsvc7xwIJMsm/RIVXFdKvMU1r1idingh5ESWKJKqZpT9Hl1hXgUYq
    on:
      APPVEYOR_REPO_TAG: true