version: '{branch}-{build}'

configuration: Release

image: Visual Studio 2022

before_build:
- cmd: dotnet restore

artifacts:
  - path: .\PandaSharp.Framework\bin\Release
    name: PandaSharp

test_script:
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor
  
build:
  publish_nuget: true
  verbosity: minimal
  
deploy:
  - provider: NuGet
    name: Push to NuGet
    api_key: $(NUGET_API_KEY)
    on:
      APPVEYOR_REPO_TAG: true